### ISSUE TITLE
bump kubernetes-client to 4.2.2

### ISSUE THREAD

**Issue by jkremser** [jvm-operators/operator-parent-pom#46]
it looks like the runtime error:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:330)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:318)
```

has been fixed in `4.2.2`

**Comment by jkremser** [comment]
done in #44
